requirejs.config({
	"baseUrl":"js",
	"paths":{
		"jquery":"libs/jquery/jquery",
		"jquery.mobile":"libs/jquery-mobile-for-synnex/jquery.mobile",
		"jquery.i18next":"libs/jquery-i18next-plugin-for-synnex/i18next.amd.withJQuery-1.8.0",
		"underscore":"libs/underscore/underscore",
		"backbone":"libs/backbone/backbone"
    }
});