

define([], function(){
	return {
		init:{
			route:{
				name:"delivery/view/carInfo",
				path:"delivery/view/carInfo"
			}
		},
		carInfo:{
			route:{
				name:"delivery/view/carInfo",
				path:"delivery/view/carInfo"
			}
		},
		departure:{
			route:{
				name:"delivery/view/departure",
				path:"delivery/view/departure"
			}
		},
		menu:{
			route:{
				name:"delivery/view/menu",
				path:"delivery/view/menu"
			}
		},
		ordinaryDelivery:{
			route:{
				name:"delivery/view/ordinaryDelivery",
				path:"delivery/view/ordinaryDelivery"
			}
		},
		productInstallation:{
			route:{
				name:"delivery/view/productInstallation",
				path:"delivery/view/productInstallation"
			}
		},
		deliveryFailure:{
			route:{
				name:"delivery/view/deliveryFailure",
				path:"delivery/view/deliveryFailure"
			}
		},
		deliveryLog:{
			route:{
				name:"delivery/view/deliveryLog",
				path:"delivery/view/deliveryLog"
			}
		},
		searchAndInquiry:{
			route:{
				name:"delivery/view/searchAndInquiry",
				path:"delivery/view/searchAndInquiry"
			}
		}
	};
});